const GAME_DATA = [
  {
    GameTitle: 'Before and After',
    GameDescription: 'Before and After Yr 2 (prefix and suffix)',
    Topic: 'Word Works and Spelling',
    Group: 'Academic',
    Level: 'Key Stage 1',
    Subject: 'English',
    GameImage: '/BeforeandAfter.png',
  },
  {
    GameTitle: 'Communication',
    GameDescription: 'Communication Yr 2 (different ways we can communicate)',
    Topic: 'Social Studies',
    Group: 'Academic',
    Level: 'Key Stage 1',
    Subject: 'Social Studies',
    GameImage: '/Communication.png',
  },
  {
    GameTitle: 'Kiddiepreneur 101',
    GameDescription: 'Kiddiepreneur 101 (Intro to Earning and Spending)',
    Topic: 'Financial Literacy',
    Group: 'Financial Literacy',
    Level: 'Financial Literacy',
    Subject: 'Financial Literacy',
    GameImage: '/Kiddiepreneur101.png',
  },
  {
    GameTitle: 'Money Matters',
    GameDescription: 'Money Matters (Intro to Key Financial Terms)',
    Topic: 'Financial Literacy',
    Group: 'Financial Literacy',
    Level: 'Financial Literacy',
    Subject: 'Financial Literacy',
    GameImage: '/MoneyMatters.png',
  },
  {
    GameTitle: 'Maths Pop',
    GameDescription:
      'Maths Pop (writing numbers in word, sequencing & ordinal numbers)',
    Topic: 'Number Sense',
    Group: 'Academic',
    Level: 'Key Stage 1',
    Subject: 'Mathematics',
    GameImage: '/MathsPop.png',
  },
  {
    GameTitle: 'Exploring Life',
    GameDescription: 'Exploring Life KS',
    Topic: 'Living Things & Non-Living Things',
    Group: 'Academic',
    Level: 'Key Stage 1',
    Subject: 'Science',
    GameImage: '/ExploringLife.png',
  },
  {
    GameTitle: 'Mathsmania City - Decimals',
    GameDescription: 'Mathsmania City - Decimal',
    Topic: 'Decimals, Fractions & Percentage',
    Group: 'Academic',
    Level: 'Key Stage 2',
    Subject: 'Mathematics',
    GameImage: '/MathsmaniaCity-Decimal.png',
  },
];

export default GAME_DATA;
